- name: Aplicação no Apache
  template: 
    src: index.html
    dest: /var/www/html/index.html

- name: Baixando imagem
  get_url: 
    url: https://img.elo7.com.br/product/zoom/11CD38F/asa-noturna-poster.jpg
    dest: /var/www/html/imagem.jpg

- name: Restartando Apache2 / HTTPD
  systemd: 
    name: "{{ item.programa }}"
    state: restarted
  when: ansible_os_family == item.familia 
  loop:
  - { programa: "apache2", familia: "Debian" }
  - { programa: "httpd", familia: "RedHat" }
